---
- hosts: compute_nodes
  tasks:
  - name: create directory
    file:
      path: /home/ansible/tmp
      state: directory
      owner: ansible
      mode: 0755
  - name: copy hosts file 
    copy:
      src: /etc/hosts
      dest: /home/ansible/tmp/hosts
      owner: ansible
      mode: 0644