---
# サーバ (hack12)
- hosts: server
  vars_files:
  - vars.yml

  tasks:
  # 各サービスのインストール
  - name: install NFS
    apt:
      name: nfs-kernel-server
      state: latest

  # 設定ファイルの適用
  # NFS
  - name: configure NFS
    copy:
      src: nfs/exports
      dest: /etc/exports
    notify: export file-system
  - name:
    shell: mount ldap01.example.com:/home /home
  handlers:
  - name: export file-system
    command: exportfs -a
