---
# 計算ノード (hack21, hack22)
# 公開鍵のコピー
- hosts: calc
  tasks:
  - name: copy crt
    copy:
      src: tls/mycacert.crt
      dest: /usr/local/share/ca-certificates/mycacert.crt
    notify: update-ca-certificates
  
  handlers:
  - name: update-ca-certificates
    shell: update-ca-certificates
