---
# サーバ (hack12)
- hosts: serv
  gather_facts: true
  remote_user: "{{ user }}"
  vars_files:
  - vars.yml

  tasks:
  # 各サービスのインストール
  - name: install slapd
    apt:
      name: slapd
      state: latest
    # notify: init configure slapd
  # handlers:
  - name: init configure slapd
    shell: echo "slapd slapd/no_configuration boolean false" | debconf-set-selections && echo "slapd slapd/domain string example.com" | debconf-set-selections && echo "slapd shared/organization string 'admin'" | debconf-set-selections && echo "slapd slapd/password1 password pass" | debconf-set-selections && echo "slapd slapd/password2 password pass" | debconf-set-selections && echo "slapd slapd/purge_database boolean true" | debconf-set-selections && echo "slapd slapd/move_old_database boolean true" | debconf-set-selections && dpkg-reconfigure -f noninteractive slapd
  - name: install LDAP
    apt:
      name: ldap-utils
      state: latest

  # 設定ファイルの適用
  # LDAP
  - name: copy ldap.conf
    copy:
      src: ldap/ldap.conf
      dest: /etc/ldap/ldap.conf
  - name: copy
    copy:
      src: ldap/init.ldif
      dest: /home/{{ user }}/init.ldif
    # notify: ldapadd init
  - name: copy
    copy:
      src: ldap/group.ldif
      dest: /home/{{ user }}/group.ldif
    # notify: ldapadd group
  - name: copy
    copy:
      src: ldap/user.ldif
      dest: /home/{{ user }}/user.ldif
    # notify: ldapadd user

  # 設定を更新
  - name: add hots
    shell: echo 192.168.122.12 ldap01.example.com >> /etc/hosts
  - name: ldapadd init
    command: ldapadd -x -D cn=admin,dc=example,dc=com -w pass -f /home/{{ user }}/init.ldif
    ignore_errors: true
  - name: ldapadd group
    command: ldapadd -x -D cn=admin,dc=example,dc=com -w pass -f /home/{{ user }}/group.ldif
    ignore_errors: true
  - name: ldapadd user
    command: ldapadd -x -D cn=admin,dc=example,dc=com -w pass -f /home/{{ user }}/user.ldif
    ignore_errors: true
  # LDAPの最初の設定 (対話になるので、予めdebconf-set-selectionsに入れておく)

# ---
# 計算ノード (hack21, hack22)
# - hosts: calculator
#   tasks:
#   - name: install LDAP and slapd
#     apt:
#       name: 
#       state: latest