---
- hosts: servers
  gather_facts: yes
  vars_files:
  - vars/{{ environment_name }}/db_info.yml
  tasks:
  - name: install apache2
    apt: 
      name: apache2
      state: latest
  - name: 
    copy:
      src: index.html
      dest: /var/www/html/index.html
  - name: 
    service:
      name: apache2
      state: started
      enabled: yes
  - name:
    lineinfile:
      path: /etc/apache2/apache2.conf
      regexp: SetEnv\s+FUEL_ENV
      line: SetEnv FUEL_ENV {{ environment_name }}
      state: present
    notify: restart_apache2

  handlers:
  - name: restart_apache2
    service:
      name: apache2
      state: restarted