---
- hosts: web
  gather_facts: true
  remote_user: saito
  vars:
  tasks:
  - name: install apache
    apt:
      name: apache2
      state: latest
  - name: Placement of config file
    copy:
      src: apache2.conf
      dest: /etc/apache2/apache2.conf
    notify: restart apache2
  - name: Placement of top page 
    copy:
      src: index.html
      dest: /var/www/index.html
  - name: enable apache service
    service:
      name: apache2
      state: started
      enabled: true
  handlers:
  - name: restart apache2
    service:
      name: apache2
      state: restarted