---
# サーバ (hack12)
#- hosts: server
#  vars_files:
#  - vars.yml

#  tasks:
  # 各サービスのインストール
#  - name: install NFS
#    apt:
#      name: nfs-kernel-server
#      state: latest

  # 設定ファイルの適用
  # NFS
#  - name: configure NFS
#    copy:
#      src: exports
#      dest: /etc/exports
#    notify: export file-system
#  - name:
#    shell: mount ldap01.example.com:/home /home
#  handlers:
#  - name: export file-system
#    command: exportfs -a
- hosts: server

  tasks: 
  - name: Installing NFS server
    apt:
      name: nfs-kernel-server
      state: latest
  
  - name: Starting NFS server
    service:
      name: nfs-kernel-server
      state: started
      enabled: yes
  
  - name: copy /etc/exports
    copy:
      src: exports
      dest: /etc/exports
  
  - name: Configure /etc/exports
    shell: exportfs -a
  
  - name: Installing NFS cliant
    apt:
      name: nfs-common
      state: latest
  
  - name: Make NFS directory
    file:
      path: /opt/example
      state: directory

  - name: Mounting NFS directory
    command: mount ldap01.example.com:/home /opt/example