---
# サーバ (hack12)
- hosts: serv
  gather_facts: true
  remote_user: "{{ user }}"
  vars_files:
  - vars.yml

  tasks:
  # 各サービスのインストール
  - name: install TLS
    apt:
      name:
      - gnutls-bin
      - ssl-cert
      state: latest

  # 設定ファイルの適用
  # TLS
  - name: copy ca.info
    copy:
      src: tls/ca.info
      dest: /etc/ssl/ca.info
    # notify: certtool generate-self-signed
  
  - name: copy ldap01.info
    copy:
      src: tls/ldap01.info
      dest: /etc/ssl/ldap01.info
    # notify: create servers certificate

  - name: copy certinfo.ldif
    copy:
      src: tls/certinfo.ldif
      dest: ./
    # notify: ldapmodify
    
  - name: copy slapd
    copy:
      src: tls/slapd
      dest: /etc/default/slapd

  # handlers:
  - name: certtool generate-self-signed
    shell: certtool --generate-privkey --bits 4096 --outfile /etc/ssl/private/mycakey.pem && certtool --generate-self-signed --load-privkey /etc/ssl/private/mycakey.pem --template /etc/ssl/ca.info --outfile /usr/local/share/ca-certificates/mycacert.crt && update-ca-certificates && certtool --generate-privkey --bits 2048 --outfile /etc/ldap/ldap01_slapd_key.pem
  - name: create servers certificate
    shell: certtool --generate-certificate --load-privkey /etc/ldap/ldap01_slapd_key.pem --load-ca-certificate /etc/ssl/certs/mycacert.pem --load-ca-privkey /etc/ssl/private/mycakey.pem --template /etc/ssl/ldap01.info --outfile /etc/ldap/ldap01_slapd_cert.pem
  - name: change groups
    file: 
      path: /etc/ldap/ldap01_slapd_key.pem
      group: openldap 
  - name: change module
    file:
      path: /etc/ldap/ldap01_slapd_key.pem
      mode: '0640'
  - name: ldapmodify
    shell: ldapmodify -Y EXTERNAL -H ldapi:/// -f certinfo.ldif
    ignore_errors: true

  - name: fetch crt
    fetch:
      src: /usr/local/share/ca-certificates/mycacert.crt
      dest: files/tls/mycacert.crt
      flat: true