- hosts: serv
  gather_facts: true

  tasks:
  #sambaのインストール
    - name: install samba
      apt: 
        name: samba
    
    #共有ディレクトリの作成
    - name: make share directory
      file:
        path: /home/lab
        state: directory
        owner: nobody
        group: nogroup
        mode: '0777'

    #sambaの設定
    - name: change samba configuration
      blockinfile:
        path: /etc/samba/smb.conf
        create: true
        insertafter: ";   write list = root, @lpadmin"
        block: |
          [lab]
             path = /home/lab
             writable = yes
             guest ok = yes  
             guest only = yes 
             create mode = 0777 
             directory mode = 0777

    #sambaをリスタート
    - name: restart smbd
      service: 
        name: smbd
        state: restarted
        enabled: true
    - name: restart nmbd
      service: 
        name: nmbd
        state: restarted
        enabled: true
