- hosts: calc
  tasks:
    - name: Installing SSSD
      apt:
        name: 
          - sssd-ldap
          - ldap-utils
        state: latest

    - name: Init sssd.conf
      copy:
        src: sssd.conf
        dest: /etc/sssd
    
    - name: Authorization to sssd.conf
      file:
        path: /etc/sssd/sssd.conf
        mode: '0600'

    - name: Starting SSSD
      service:
        name: sssd
        state: restarted
        #enabled: yes
    
    - name: Automatically create home directory
      command: pam-auth-update --enable mkhomedir